CREATE CONSTRAINT user_id_unique IF NOT EXISTS
FOR (u:User)
REQUIRE u.id IS UNIQUE;

CREATE CONSTRAINT pet_id_unique IF NOT EXISTS
FOR (p:Pet)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT trait_id_unique IF NOT EXISTS
FOR (t:Trait)
REQUIRE t.id IS UNIQUE;
